import io
import json
import logging
import re
import zipfile
from typing import Any, Dict, List, Optional

import httpx

from ..models.schemas import CommerceCreationOutput, EngineStage, ProductVariant

logger = logging.getLogger(__name__)


def _slugify(text: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[-\s]+", "-", slug).strip("-") or "store"


def _build_shopify_product_json(
    commerce: CommerceCreationOutput,
    product_name: str,
) -> Dict[str, Any]:
    title = commerce.product_title or (commerce.seo_titles[0] if commerce.seo_titles else product_name)
    body_html = commerce.product_description_html or commerce.product_description
    variants: List[Any] = commerce.variants or [ProductVariant()]

    variant_list = []
    for v in variants:
        if hasattr(v, "model_dump"):
            vd = v.model_dump()
        else:
            vd = v
        variant_list.append({
            "title": vd.get("title", "Default"),
            "price": vd.get("price", "29.99"),
            "compare_at_price": vd.get("compare_at_price"),
            "sku": vd.get("sku", ""),
            "inventory_management": None,
            "inventory_policy": "continue",
            "fulfillment_service": "manual",
            "requires_shipping": True,
        })

    if not variant_list:
        variant_list = [{"title": "Default", "price": "29.99", "sku": ""}]

    return {
        "product": {
            "title": title,
            "body_html": body_html,
            "vendor": "XtarzVA Store Builder",
            "product_type": commerce.collection_title or "General",
            "tags": ", ".join(commerce.tags) if commerce.tags else "",
            "status": "draft",
            "variants": variant_list,
            "metafields_global_title_tag": commerce.seo_meta_title or title,
            "metafields_global_description_tag": commerce.seo_meta_description or body_html[:160],
        }
    }


def _readme_text(product_name: str) -> str:
    return f"""XtarzVA Store Builder Export — {product_name}
================================================

This ZIP contains Shopify-ready assets generated by XtarzVA Store Builder.

CONTENTS
--------
- product.json          Shopify product import format (use Shopify Admin API or a CSV/JSON importer)
- store-content/        Page copy for your storefront
  - homepage-hero.md    Hero section headline & subheadline
  - about-page.md       About page snippet
  - collection.md       Collection title & description
  - product-page.html   Full product description (HTML)
- images/               Product images (best-effort download)
- image-manifest.json   Image URLs if local download failed
- theme-settings.json   Theme-ready JSON for Dawn/Online Store 2.0 customization

HOW TO IMPORT TO SHOPIFY
------------------------
1. Products → Add product → paste content from store-content/product-page.html
2. Set title, tags, and SEO fields from product.json
3. Upload images from images/ folder as product media
4. Create a collection using store-content/collection.md
5. Customize your theme homepage with store-content/homepage-hero.md
6. For bulk import, use Shopify's product CSV template or the Admin API with product.json

No Shopify API keys are required — this is a manual import package.

Generated by XtarzVA — https://xtarzva.site
"""


async def _fetch_image(client: httpx.AsyncClient, url: str, index: int) -> Optional[tuple[str, bytes]]:
    try:
        resp = await client.get(url, follow_redirects=True, timeout=20.0)
        resp.raise_for_status()
        content_type = resp.headers.get("content-type", "image/jpeg")
        ext = "jpg"
        if "png" in content_type:
            ext = "png"
        elif "webp" in content_type:
            ext = "webp"
        elif "gif" in content_type:
            ext = "gif"
        return f"product-{index + 1}.{ext}", resp.content
    except Exception as e:
        logger.warning(f"Failed to fetch image {url}: {e}")
        return None


async def build_store_zip(
    engine_data: Dict[str, Any],
    run_id: str,
) -> tuple[bytes, str]:
    """Build a ZIP archive from a completed commerce_creation run."""
    raw = engine_data.get(EngineStage.COMMERCE_CREATION.value)
    if not raw:
        raise ValueError("No store builder output found for this run")

    commerce = CommerceCreationOutput.model_validate(raw)
    product = engine_data.get("selected_product") or engine_data.get(EngineStage.PRODUCT_INTELLIGENCE.value) or {}
    product_name = product.get("product_name", "store") if isinstance(product, dict) else "store"
    slug = _slugify(product_name)

    product_json = _build_shopify_product_json(commerce, product_name)
    theme_json = commerce.store_theme_json or {
        "hero": {
            "headline": commerce.homepage_hero_headline,
            "subheadline": commerce.homepage_hero_subheadline,
        },
        "collection": {
            "title": commerce.collection_title,
            "description": commerce.collection_description,
        },
        "brand": {
            "about": commerce.about_page_snippet,
        },
        "colors": {"primary": "#1a1a2e", "accent": "#e94560"},
    }

    image_urls: List[str] = commerce.generated_image_urls or []
    fetched_images: List[tuple[str, bytes]] = []
    failed_urls: List[str] = []

    if image_urls:
        async with httpx.AsyncClient() as client:
            for i, url in enumerate(image_urls):
                result = await _fetch_image(client, url, i)
                if result:
                    fetched_images.append(result)
                else:
                    failed_urls.append(url)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.txt", _readme_text(product_name))
        zf.writestr("product.json", json.dumps(product_json, indent=2))
        zf.writestr("theme-settings.json", json.dumps(theme_json, indent=2))

        hero_md = f"# {commerce.homepage_hero_headline}\n\n{commerce.homepage_hero_subheadline}\n"
        zf.writestr("store-content/homepage-hero.md", hero_md)
        zf.writestr("store-content/about-page.md", commerce.about_page_snippet or "")
        zf.writestr(
            "store-content/collection.md",
            f"# {commerce.collection_title}\n\n{commerce.collection_description}\n",
        )
        zf.writestr(
            "store-content/product-page.html",
            commerce.product_description_html or commerce.product_description,
        )
        zf.writestr(
            "store-content/seo-meta.txt",
            f"Title: {commerce.seo_meta_title}\nDescription: {commerce.seo_meta_description}\n",
        )
        zf.writestr(
            "store-content/ad-hooks.txt",
            "\n".join(f"- {h}" for h in commerce.ad_copy_hooks),
        )

        for filename, content in fetched_images:
            zf.writestr(f"images/{filename}", content)

        zf.writestr(
            "image-manifest.json",
            json.dumps({"urls": image_urls, "failed_downloads": failed_urls}, indent=2),
        )

    return buf.getvalue(), f"{slug}-store-{run_id[:8]}.zip"
